export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const monthOptions = monthNames.map((item) => ({
  value: item,
  label: item,
}));

export const facultiesOption = [
  { value: "Faculty of Science", label: "Faculty of Science" },
  { value: "Faculty of Engineering", label: "Faculty of Engineering" },
  {
    value: "Faculty of Arts and Humanities",
    label: "Faculty of Arts and Humanities",
  },
  { value: "Faculty of Social Sciences", label: "Faculty of Social Sciences" },
  { value: "Faculty of Business", label: "Faculty of Business" },
  { value: "Faculty of Education", label: "Faculty of Education" },
  { value: "Faculty of Medicine", label: "Faculty of Medicine" },
  { value: "Faculty of Law", label: "Faculty of Law" },
  { value: "Faculty of Agriculture", label: "Faculty of Agriculture" },
  {
    value: "Faculty of Computer Science and Information Technology",
    label: "Faculty of Computer Science and Information Technology",
  },
  {
    value: "Faculty of Environmental Studies",
    label: "Faculty of Environmental Studies",
  },
  {
    value: "Faculty of Architecture and Design",
    label: "Faculty of Architecture and Design",
  },
  { value: "Faculty of Fine Arts", label: "Faculty of Fine Arts" },
  { value: "Faculty of Music", label: "Faculty of Music" },
  { value: "Faculty of Health Sciences", label: "Faculty of Health Sciences" },
  { value: "Faculty of Pharmacy", label: "Faculty of Pharmacy" },
  { value: "Faculty of Dentistry", label: "Faculty of Dentistry" },
  { value: "Faculty of Nursing", label: "Faculty of Nursing" },
  {
    value: "Faculty of Veterinary Medicine",
    label: "Faculty of Veterinary Medicine",
  },
  { value: "Faculty of Forestry", label: "Faculty of Forestry" },
  { value: "Faculty of Horticulture", label: "Faculty of Horticulture" },
  { value: "Faculty of Fisheries", label: "Faculty of Fisheries" },
  {
    value: "Faculty of Maritime Studies",
    label: "Faculty of Maritime Studies",
  },
  {
    value: "Faculty of International Relations",
    label: "Faculty of International Relations",
  },
  { value: "Faculty of Communication", label: "Faculty of Communication" },
  { value: "Faculty of Journalism", label: "Faculty of Journalism" },
  {
    value: "Faculty of Religious Studies",
    label: "Faculty of Religious Studies",
  },
  { value: "Faculty of Sports Sciences", label: "Faculty of Sports Sciences" },
  {
    value: "Faculty of Library and Information Science",
    label: "Faculty of Library and Information Science",
  },
  { value: "Faculty of Ethnic Studies", label: "Faculty of Ethnic Studies" },
  { value: "Faculty of Gender Studies", label: "Faculty of Gender Studies" },
  { value: "Faculty of Humanities", label: "Faculty of Humanities" },
  { value: "Faculty of Classics", label: "Faculty of Classics" },
  {
    value: "Faculty of Military Sciences",
    label: "Faculty of Military Sciences",
  },
  {
    value: "Faculty of Tourism and Hospitality",
    label: "Faculty of Tourism and Hospitality",
  },
];

export const departmentOptions = [
  { value: "Computer Science", label: "Computer Science" },
  { value: "Mechanical Engineering", label: "Mechanical Engineering" },
  { value: "Electrical Engineering", label: "Electrical Engineering" },
  { value: "Civil Engineering", label: "Civil Engineering" },
  { value: "Biology", label: "Biology" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Physics", label: "Physics" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Economics", label: "Economics" },
  { value: "Psychology", label: "Psychology" },
  { value: "Environmental Science", label: "Environmental Science" },
  { value: "Sociology", label: "Sociology" },
  { value: "Anthropology", label: "Anthropology" },
  { value: "Political Science", label: "Political Science" },
  { value: "History", label: "History" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Linguistics", label: "Linguistics" },
  { value: "Literature", label: "Literature" },
  { value: "Art and Design", label: "Art and Design" },
  { value: "Architecture", label: "Architecture" },
  { value: "Music", label: "Music" },
  {
    value: "Theatre and Performance Studies",
    label: "Theatre and Performance Studies",
  },
  { value: "Business Administration", label: "Business Administration" },
  { value: "Finance", label: "Finance" },
  { value: "Marketing", label: "Marketing" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "Accounting", label: "Accounting" },
  { value: "Education", label: "Education" },
  { value: "Nursing", label: "Nursing" },
  { value: "Public Health", label: "Public Health" },
  { value: "Law", label: "Law" },
  { value: "Criminology", label: "Criminology" },
  { value: "Geography", label: "Geography" },
  { value: "Geology", label: "Geology" },
  { value: "Astronomy", label: "Astronomy" },
  { value: "Materials Science", label: "Materials Science" },
  { value: "Biomedical Engineering", label: "Biomedical Engineering" },
  { value: "Chemical Engineering", label: "Chemical Engineering" },
  { value: "Aerospace Engineering", label: "Aerospace Engineering" },
  { value: "Oceanography", label: "Oceanography" },
  { value: "Veterinary Science", label: "Veterinary Science" },
  { value: "Agriculture", label: "Agriculture" },
  { value: "Forestry", label: "Forestry" },
  { value: "Horticulture", label: "Horticulture" },
  {
    value: "Food Science and Technology",
    label: "Food Science and Technology",
  },
  { value: "International Relations", label: "International Relations" },
  {
    value: "Media and Communication Studies",
    label: "Media and Communication Studies",
  },
  { value: "Journalism", label: "Journalism" },
  { value: "Religious Studies", label: "Religious Studies" },
  { value: "Urban Planning", label: "Urban Planning" },
  { value: "Sports Science", label: "Sports Science" },
  {
    value: "Library and Information Science",
    label: "Library and Information Science",
  },
  { value: "Ethnic Studies", label: "Ethnic Studies" },
  { value: "Gender Studies", label: "Gender Studies" },
  { value: "Classical Studies", label: "Classical Studies" },
];
